name: native_share_android
description: "A Flutter plugin for sharing files and sending emails natively on Android"
version: 0.0.4
homepage: https://github.com/Gloomy699/native_share_android
repository: https://github.com/Gloomy699/native_share_android
issue_tracker: https://github.com/Gloomy699/native_share_android/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.native_share_android.native_share_android
        pluginClass: NativeShareAndroidPlugin

